import type { CodegenConfig } from '@graphql-codegen/cli';

// For local development, fetch from running API or use source schema (JSON introspection)
// For CI/CD, use: schema: 'apps/api/src/schema.gql' after building API
const config: CodegenConfig = {
  schema: process.env.CI
    ? './libs/shared/src/generated/schema.json'
    : 'http://localhost:3000/graphql',
  documents: [
    'apps/web/src/**/*.graphql',
    'apps/web/src/**/*.tsx',
    '!apps/web/src/components/notifications/**',
    '!apps/web/src/components/tags/TagCloud.tsx',
    '!apps/web/src/components/tags/TagManager.tsx',
    '!apps/web/src/components/tags/TagRecommendation.tsx',
    '!apps/web/src/components/tags/TagSelector.tsx',
    '!apps/web/src/components/tags/TagStats.tsx',
    '!apps/web/src/components/contracts/BatchActions.tsx',
    '!apps/web/src/pages/forgot-password.tsx',
    '!apps/web/src/pages/settings/profile.tsx',
  ],
  generates: {
    'libs/shared/src/generated/graphql.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable */\n// @ts-nocheck\n// This file is auto-generated by GraphQL Codegen - DO NOT EDIT',
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-react-apollo',
      ],
      config: {
        withHooks: true,
        withComponent: false,
        withHOC: false,
        withRefetchFn: false,
        apolloReactCommonImportFrom: '@apollo/client/react',
        apolloReactHooksImportFrom: '@apollo/client/react',
        addDocBlocks: false,
        scalars: {
          DateTime: 'string',
          Decimal: 'string',
        },
      },
    },
    'libs/shared/src/generated/schema.json': {
      plugins: ['introspection'],
    },
  },
  ignoreNoDocuments: true,
};

export default config;
