import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'apps/api/src/schema.gql',
  documents: ['apps/web/src/**/*.graphql', 'apps/web/src/**/*.tsx'],
  generates: {
    'libs/shared/src/generated/graphql.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable */\n// @ts-nocheck\n// This file is auto-generated by GraphQL Codegen - DO NOT EDIT',
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-react-apollo',
      ],
      config: {
        withHooks: true,
        withComponent: false,
        withHOC: false,
        withRefetchFn: false,
        apolloReactCommonImportFrom: '@apollo/client/react',
        apolloReactHooksImportFrom: '@apollo/client/react',
        addDocBlocks: false,
        scalars: {
          DateTime: 'string',
          Decimal: 'string',
        },
      },
    },
    'libs/shared/src/generated/schema.json': {
      plugins: ['introspection'],
    },
  },
  ignoreNoDocuments: true,
};

export default config;
